# Generated by Django 3.2.25 on 2025-06-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_watch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootWear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher/')),
            ],
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher/')),
            ],
        ),
        migrations.CreateModel(
            name='WomenDress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Watch',
            new_name='Beauty',
        ),
    ]
