# Generated by Django 3.2.25 on 2025-07-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_alter_cartdress_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/'),
        ),
    ]
