# Generated by Django 3.2.25 on 2025-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_alter_cartdress_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
