# Generated by Django 3.2.25 on 2025-07-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_grocerycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerycart',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
