# Generated by Django 3.2.25 on 2025-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_alter_grocerycart_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
            ],
        ),
    ]
